import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Footer from '@/components/Footer/Footer';
import "./globals.css";
import FooterSection from "@/components/Footer/FooterSection";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FoodTuck",
  description: "Generated by Roman Ayub Khan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        {children}
   <div className=' bg-[#000000] overflow-hidden px-[12vw] py-10 '>

<Footer/>

</div>
<FooterSection/>
      </body>
    </html>
  );
}
